// ignore_for_file: unnecessary_string_escapes, equal_keys_in_map

import 'package:get/get.dart';

final class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        //ENGLISH LANGUAGE
        'en_US': {
          'Select Language': 'Select Language',
          'Continue': 'Continue',
          "Welcome to Leak Report": "Welcome to Leak Report",
          "Easily report water leaks in your home or neighborhood.":
              "Easily report water leaks in your home or neighborhood.",
          "Fast & Simple Reporting": "Fast & Simple Reporting",
          "Upload photos, and select leak type, all in one step.":
              "Upload photos, and select leak type, all in one step.",
          "Stay Updated": "Stay Updated",
          "Track your report, get advice for household leaks, or call emergency services instantly.":
              "Track your report, get advice for household leaks, or call emergency services instantly.",
          'Skip': 'Skip',
          'Start Reporting': 'Start Reporting',
          'Welcome Back': 'Welcome Back',
          'Create an account or log in to explore about our app':
              'Create an account or log in to explore about our app',
          'Log In': 'Log In',
          'Sign Up': 'Sign Up',
          'Email address*': 'Email address*',
          'Email': 'Email',
          'Enter Your Email': 'Enter Your Email',
          'Password*': 'Password*',
          'password': 'password',
          'Enter Your Password': 'Enter Your Password',
          'Forgot password?': 'Forgot password?',
          'Log in': 'Log in',
          'or': 'or',
          'Continue with Google': 'Continue with Google',
          'Full name*': 'Full name*',
          'Full Name': 'Full Name',
          'Enter Your Name': 'Enter Your Name',
          'Mobile number*': 'Mobile number*',
          'Mobile Number': 'Mobile Number',
          'Enter Mobile Number': 'Enter Mobile Number',
          'Email address*': 'Email address*',
          'Email Address': 'Email Address',
          'Password*': 'Password*',
          'Password': 'Password',
          'Enter Your Password': 'Enter Your Password',
          'Confirm Password*': 'Confirm Password*',
          'Cofirm Password': 'Cofirm Password',
          'Enter Confirm Password': 'Enter Confirm Password',
          'Nama Account No': 'Nama Account No',
          'Nama Account': 'Nama Account',
          'Enter Nama Account': 'Enter Nama Account',
          'Sign Up': 'Sign Up',
          'Please check your email!': 'Please check your email!',
          'We\'ve send a 6-digit confirmation code, please enter the code in below box to verify your email.':
              'We\'ve send a 6-digit confirmation code, please enter the code in below box to verify your email.',
          'Verify': 'Verify',
          'Account Created Successfully!': 'Account Created Successfully!',
          'Log in now': 'Log in now',
          'Forgot your password': 'Forgot your password',
          'Please enter the email address associated with your account, and we\'ll email you a link to reset your password.':
              'Please enter the email address associated with your account, and we\'ll email you a link to reset your password.',
          'Reset password': 'Reset password',
          'Set your password?': 'Set your password?',
          'Please enter your new password and confirm it below to reset your password.':
              'Please enter your new password and confirm it below to reset your password.',
          'New Password': 'New Password',
          'Please enter a password': 'Please enter a password',
          'Password must be at least 8 characters':
              'Password must be at least 8 characters',
          'Confirm Password': 'Confirm Password',
          'Please confirm your password': 'Please confirm your password',
          'Password must be at least 8 characters':
              'Password must be at least 8 characters',
          'Passwords do not match': 'Passwords do not match',
          'Update': 'Update',
          'Password updated Successfully!': 'Password updated Successfully!',
          'Home': 'Home',
          'Notification': 'Notification',
          'Profile': 'Profile',
          'Leak Reports': 'Leak Reports',
          "Error loading data": "Error loading data",
          'Did you spot a leak?': 'Did you spot a leak?',
          'Call Emergency Service': 'Call Emergency Service',
          'Welcome back': 'Welcome back',
          'Report Details': 'Report Details',
          'Leak Images': 'Leak Images',
          'Report Information': 'Report Information',
          'Report ID': 'Report ID',
          'Type of Leak': 'Type of Leak',
          'Submitted On': 'Submitted On',
          'Address': 'Address',
          'Note': 'Note',
          'Status Timeline': 'Status Timeline',
          'Reported': 'Reported',
          'Under Review': 'Under Review',
          'Resolved': 'Resolved',
          'Report a Leak': 'Report a Leak',
          'Add Leak Images': 'Add Leak Images',
          "Tap to upload up to 3 images": "Tap to upload up to 3 images",
          "No leak types found": "No leak types found",
          'Pin the Address': 'Pin the Address',
          'Address preview': 'Address preview',
          'Additional Notes (Optional)': 'Additional Notes (Optional)',
          'Write here...': 'Write here...',
          'Send Report': 'Send Report',
          'Search here': 'Search here',
          'Report Send Successfully!': 'Report Send Successfully!',
          'Go to home': 'Go to home',
          'Notifications': 'Notifications',
          'My Profile': 'My Profile',
          'Settings': 'Settings',
          'Language': 'Language',
          'Help Centre': 'Help Centre',
          'Privacy Policy': 'Privacy Policy',
          'Log Out': 'Log Out',
          'Gender': 'Gender',
          'Mobile number': 'Mobile number',
          'Edit Profile': 'Edit Profile',
          'Full name': 'Full name',
          'Mobile number': 'Mobile number',
          'Select Gender': 'Select Gender',
          'Please select gender': 'Please select gender',
          'Save changes': 'Save changes',
          'Change Password': 'Change Password',
          'Delete Account': 'Delete Account',
          'Are you sure want to delete your account?':
              'Are you sure want to delete your account?',
          'Keep it': 'Keep it',
          'Delete': 'Delete',
          'Old Password': 'Old Password',
          'Enter Old Password': 'Enter Old Password',
          'New Password': 'New Password',
          'Enter New Password': 'Enter New Password',
          'Update Password': 'Update Password',
          'Help Center': 'Help Center',
          'Privacy & Policy': 'Privacy & Policy',
          'Choose Your Language': 'Choose Your Language',
          'Report a Leak': 'Report a Leak',
          'Selected Leak Type': 'Selected Leak Type',
          "Do you want to exit the app?": "Do you want to exit the app?",
          'No': 'No',
          'Yes': 'Yes',
          'Nama Account No (Optional)': 'Nama Account No (Optional)',
          'Please select leak type': 'Please select leak type',
          'Please select an image': 'Please select an image',
          "Gallery": "Gallery",
          "Camera": "Camera",
          'Password does not match': 'Password does not match',
          'Password must be at least 6 characters':
              'Password must be at least 6 characters',
        },
        'ar_AR': {
          'Password must be at least 6 characters':
              'يجب أن تحتوي كلمة المرور على 6 أحرف على الأقل',
          'Password does not match': 'كلمة المرور غير متطابقة',
          "Gallery": "المعرض",
          "Camera": "الكاميرا",
          "Please select leak type": "يرجى اختيار نوع التسريب",
          "Please select an image": "يرجى اختيار صورة",
          'Select Language': 'اختر اللغة',
          'Continue': 'متابعة',
          "Welcome to Leak Report": "مرحبًا بك في تقرير التسرب",
          "Easily report water leaks in your home or neighborhood.":
              "قم بالإبلاغ عن تسربات المياه في منزلك أو حيّك بسهولة.",
          "Fast & Simple Reporting": "إبلاغ سريع وبسيط",
          "Upload photos, and select leak type, all in one step.":
              "قم بتحميل الصور، واختر نوع التسرب، كل ذلك في خطوة واحدة.",
          "Stay Updated": "ابقَ على اطلاع",
          "Track your report, get advice for household leaks, or call emergency services instantly.":
              "تابع تقريرك، واحصل على نصائح حول تسربات المنزل، أو اتصل بخدمات الطوارئ فورًا.",
          "Skip": "تخطي",
          "Start Reporting": "ابدأ بالإبلاغ",
          'Welcome Back': 'مرحبًا بعودتك',
          'Create an account or log in to explore about our app':
              'أنشئ حسابًا أو سجّل الدخول لاستكشاف تطبيقنا',
          'Log In': 'تسجيل الدخول',
          'Sign Up': 'إنشاء حساب',
          'Email address*': 'عنوان البريد الإلكتروني*',
          'Email': 'البريد الإلكتروني',
          'Enter Your Email': 'أدخل بريدك الإلكتروني',
          'Password*': 'كلمة المرور*',
          'password': 'كلمة المرور',
          'Enter Your Password': 'أدخل كلمة المرور',
          'Forgot password?': 'نسيت كلمة المرور؟',
          'Log in': 'تسجيل الدخول',
          'or': 'أو',
          'Continue with Google': 'المتابعة عبر جوجل',
          'Full name*': 'الاسم الكامل*',
          'Full Name': 'الاسم الكامل',
          'Enter Your Name': 'أدخل اسمك',
          'Mobile number*': 'رقم الجوال*',
          'Mobile Number': 'رقم الجوال',
          'Enter Mobile Number': 'أدخل رقم الجوال',
          'Email address*': 'عنوان البريد الإلكتروني*',
          'Email Address': 'عنوان البريد الإلكتروني',
          'Password*': 'كلمة المرور*',
          'Password': 'كلمة المرور',
          'Enter Your Password': 'أدخل كلمة المرور',
          'Confirm Password*': 'تأكيد كلمة المرور*',
          'Cofirm Password': 'تأكيد كلمة المرور',
          'Enter Confirm Password': 'أدخل تأكيد كلمة المرور',
          'Nama Account No': 'رقم حساب نما',
          'Nama Account': 'حساب نما',
          'Enter Nama Account': 'أدخل حساب نما',
          'Sign Up': 'إنشاء حساب',
          'Please check your email!': 'يرجى التحقق من بريدك الإلكتروني!',
          'We\'ve send a 6-digit confirmation code, please enter the code in below box to verify your email.':
              'لقد أرسلنا رمز تأكيد مكون من 6 أرقام، يرجى إدخال الرمز في الصندوق أدناه للتحقق من بريدك الإلكتروني.',
          'Verify': 'تحقق',
          'Account Created Successfully!': 'تم إنشاء الحساب بنجاح!',
          'Log in now': 'تسجيل الدخول الآن',
          'Forgot your password': 'نسيت كلمة المرور',
          'Please enter the email address associated with your account, and we\'ll email you a link to reset your password.':
              'يرجى إدخال عنوان البريد الإلكتروني المرتبط بحسابك، وسنرسل لك رابطًا لإعادة تعيين كلمة المرور.',
          'Reset password': 'إعادة تعيين كلمة المرور',
          'Set your password?': 'هل تريد تعيين كلمة المرور؟',
          'Please enter your new password and confirm it below to reset your password.':
              'يرجى إدخال كلمة المرور الجديدة وتأكيدها أدناه لإعادة تعيين كلمة المرور.',
          'New Password': 'كلمة المرور الجديدة',
          'Please enter a password': 'يرجى إدخال كلمة المرور',
          'Password must be at least 8 characters':
              'يجب أن تكون كلمة المرور 8 أحرف على الأقل',
          'Confirm Password': 'تأكيد كلمة المرور',
          'Please confirm your password': 'يرجى تأكيد كلمة المرور',
          'Passwords do not match': 'كلمات المرور غير متطابقة',
          'Update': 'تحديث',
          'Password updated Successfully!': 'تم تحديث كلمة المرور بنجاح!',
          'Home': 'الرئيسية',
          'Notification': 'الإشعارات',
          'Profile': 'الملف الشخصي',
          'Leak Reports': 'تقارير التسرب',
          'Error loading data': 'حدث خطأ أثناء تحميل البيانات',
          'Did you spot a leak?': 'هل لاحظت وجود تسرب؟',
          'Call Emergency Service': 'اتصل بخدمة الطوارئ',
          'Welcome back': 'مرحباً بعودتك',
          'Report Details': 'تفاصيل التقرير',
          'Leak Images': 'صور التسرب',
          'Report Information': 'معلومات التقرير',
          'Report ID': 'معرف التقرير',
          'Type of Leak': 'نوع التسرب',
          'Submitted On': 'تم الإرسال في',
          'Address': 'العنوان',
          'Note': 'ملاحظة',
          'Status Timeline': 'الجدول الزمني للحالة',
          'Reported': 'تم الإبلاغ',
          'Under Review': 'قيد المراجعة',
          'Resolved': 'تم الحل',
          'Report a Leak': 'الإبلاغ عن تسرب',
          'Add Leak Images': 'إضافة صور التسرب',
          'Tap to upload up to 3 images': 'اضغط لتحميل ما يصل إلى 3 صور',
          'No leak types found': 'لم يتم العثور على أنواع تسرب',
          'Pin the Address': 'تثبيت العنوان',
          'Address preview': 'معاينة العنوان',
          'Additional Notes (Optional)': 'ملاحظات إضافية (اختياري)',
          'Write here...': 'اكتب هنا...',
          'Send Report': 'إرسال التقرير',
          'Search here': 'ابحث هنا',
          'Report Send Successfully!': 'تم إرسال التقرير بنجاح!',
          'Go to home': 'الذهاب إلى الصفحة الرئيسية',
          'Notifications': 'الإشعارات',
          'My Profile': 'ملفي الشخصي',
          'Settings': 'الإعدادات',
          'Language': 'اللغة',
          'Help Centre': 'مركز المساعدة',
          'Privacy Policy': 'سياسة الخصوصية',
          'Log Out': 'تسجيل الخروج',
          'Gender': 'النوع',
          'Mobile number': 'رقم الجوال',
          'Edit Profile': 'تعديل الملف الشخصي',
          'Full name': 'الاسم الكامل',
          'Select Gender': 'اختر الجنس',
          'Please select gender': 'يرجى اختيار الجنس',
          'Save changes': 'حفظ التغييرات',
          'Change Password': 'تغيير كلمة المرور',
          'Delete Account': 'حذف الحساب',
          'Are you sure want to delete your account?':
              'هل أنت متأكد أنك تريد حذف حسابك؟',
          'Keep it': 'احتفظ به',
          'Delete': 'حذف',
          'Old Password': 'كلمة المرور القديمة',
          'Enter Old Password': 'أدخل كلمة المرور القديمة',
          'New Password': 'كلمة المرور الجديدة',
          'Enter New Password': 'أدخل كلمة المرور الجديدة',
          'Update Password': 'تحديث كلمة المرور',
          'Help Center': 'مركز المساعدة',
          'Privacy & Policy': 'الخصوصية والسياسة',
          'Choose Your Language': 'اختر لغتك',
          'Report a Leak': 'الإبلاغ عن تسرب',
          'Selected Leak Type': 'نوع التسرب المحدد',
          "Do you want to exit the app?": "هل تريد الخروج من التطبيق؟",
          "No": "لا",
          "Yes": "نعم",
          'Nama Account No (Optional)': 'رقم حساب نما (اختياري)',
        },
      };
}
